---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-canary
  namespace: canary
  annotations:
    nginx.ingress.kubernates.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Canary-Release"
spec:
  backend:
    serviceName: web-canary
    servicePort: 80
  rules:
<<<<<<< HEAD
  - host: example.com
    http:
     paths:
     - path: /
       pathType: Prefix
=======
  - http:
     paths:
     - path: /
>>>>>>> f8c01c54340a742b514279f07d6c45366a7b063b
       backend:
         serviceName: web-canary
         servicePort: 80

