---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-stable
  namespace: canary
  annotations:
    nginx.ingress.kubernates.io/rewrite-target: /
spec:
  backend:
    serviceName: web-stable
    servicePort: 80
  rules:
<<<<<<< HEAD
  - host: example.com
    http:
     paths:
     - path: /
       pathType: Prefix
=======
  - http:
     paths:
     - path: /
>>>>>>> f8c01c54340a742b514279f07d6c45366a7b063b
       backend:
         serviceName: web-stable
         servicePort: 80

