---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-canary
  namespace: canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    #nginx.ingress.kubernetes.io/canary-by-header: "X-Canary-Release"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - host: canary.example.com
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service: 
           name: web-canary 
           port:
             number: 80

