---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-stable
  namespace: canary
spec:
  rules:
  - host: canary.example.com
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: web-stable 
           port:
             number: 80

