---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 100M
  accessModes:
    - ReadWriteOnce

