---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  resources:
    requests:
      storage: 100M
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-csi-storage-class
