---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
    - name: storage-pod
      image: "stitrace/nginx-kubernates-intro:0.0.4"
      volumeMounts:
      - name: persistent-storage
        mountPath: "/data"
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: storage-pvc
