---
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: hostapath.csi.k8s.io
metadata:
  name: hostpath-csi-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
