---
apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
    - name: storage-pod
      image: busybox
      volumeMounts:
      - name: ps
        mountPath: "/data"
      command: ["/bin/sh", "-ec", "sleep 1000"]
  volumes:
  - name: ps
    persistentVolumeClaim:
      claimName: storage-pvc
