---
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: hostpath.csi.k8s.io
metadata:
  name: hostpath-csi-sc
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
