---
apiVersion: v1 
kind: Pod
metadata:
 name: nginx-kubernates-intro
 namespace: default
 labels:
  app: hw1
spec:
 containers:
 - name: web-server
   image: stitrace/nginx-kubernates-intro:0.0.1
   imagePullPolicy: IfNotPresent
   volumeMounts:
   - name: app
     mountPath: /var/www/localhost/htdocs
 initContainers:
 - name: init-web-server
   #image: busybox:1.32.0-musl
   image: busybox:1.31.0
   imagePullPolicy: IfNotPresent
   command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
   volumeMounts:
   - name: app
     mountPath: /app
 volumes:
 - name: app
   emptyDir: {}
 serviceAccount: default

