---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-ro
  namespace: prometheus
subjects:
- kind: Group
  namespace: prometheus
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: pods-ro
  apiGroup: rbac.authorization.k8s.io
  
