---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-ro
  namespace: prometheus
subjects:
- kind: User
  name: carol
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prometheus-pods-ro
  apiGroup: rbac.authorization.k8s.io
  
