---
apiVersion: v1
kind: Service
metadata:
  name: example-app-svc
spec:
  selector:
    app: example-app
  type: ClusterIP
  ports:
    - name: www-port
      protocol: TCP
      port: 8010
      targetPort: 8010
    - name: exporter-port
      protocol: TCP
      port: 9113
      targetPort: 9113