---
server:
 affinity: ""
 nodeSelector: |
  cloud.local/nodepool: infra-pool
 affinity: |
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist

standalone:
  enabled: false

ha:
  enabled: true
  replicas: 3
  raft:
   enabled: true
   config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "vault:8200"
        cluster_address = "vault:8201"
      }
      storage "consul" {
        path = "vault"
        address = "consul.bitnami-consul:8500"
      }

ui:
  enabled: true
  serviceType: "ClusterIP"

ingress:
 enabled: true
 labels: {}
 annotations:
   kubernetes.io/ingress.class: nginx
   kubernetes.io/tls-acme: "true"
 hosts:
   - host: vault.192.168.150.240.nip.io

dataStorage:
  enabled: true
  storageClass: nfs-client
  accessMode: ReadWriteOnce

auditStorage:
  enabled: true
  storageClass: nfs-client
  accessMode: ReadWriteOnce
  
