---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cartservice-stage

namePrefix: stage-

commonAnnotations:
  environment: stage 

namespace: hipster-shop-stage

bases:
  - ../../base
