controller:
  replicaCount: 2

  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nginx-ingress
          topologyKey: kubernetes.io/hostname

  nodeSelector: 
    cloud.local/nodepool: infra-pool
  service:
   externalIPs:
    - 192.168.150.240
    - 192.168.150.241

  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", 
      "request_id": "$req_id", 
      "proxy_upstream_name": "$proxy_upstream_name",
      "proxy_alternative_upstream_name": "$proxy_alternative_upstream_name",
      "upstream_status": "$upstream_status",
      "upstream_addr": "$upstream_addr",
      "x-forward-for": "$proxy_add_x_forwarded_for",
      "http_request":{"request_method": "$request_method", "request_url": "$host$request_uri",
      "status": $status,"requestSize": "$request_length", "response_size": "$upstream_response_length",
      "user_agent": "$http_user_agent", "remote_ip": "$remote_addr", "referer": "$http_referer",
      "latency": "$upstream_response_time", "protocol":"$server_protocol"}}'

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "nginx-ingress"
      namespaceSelector: {}
      scrapeInterval: 30s


