---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hipster-shop
  labels:
    app: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort | default 30080 }}
{{- end }}

