---
apiVersion: v1 
kind: Pod
metadata:
 name: nginx-kubernates-intro
 labels:
  app: hw1
spec:
 containers:
 - name: web-server
   image: stitrace/nginx-kubernates-intro:0.0.1
   imagePullPolicy: IfNotPresent
   volumeMounts:
   - name: app
     mountPath: /var/www/localhost/htdocs
 initContainers:
 - name: init-web-server
   image: busybox:1.31.0
   imagePullPolicy: IfNotPresent
   command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
   volumeMounts:
   - name: app
     mountPath: /app
 volumes:
 - name: app
   emptyDir: {}
 serviceAccount: default

